name = "Restitution"
author = "RyzechDev"
version = "1.0.2-patch"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c48897cb3344936ed4143556d75c8b8c2601f95ab1b719558598612fc81ab129"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.102"
