name = "Restitution"
author = "RyzechDev"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0b18be3d5a7210c638d16e7933a3c0ccad7a1ec15284fea908fd66a483d66b8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.102"
