Platform.mods.kubejs.name = 'Restitution'
function registerAntiblock(event, color, displayname) {
    event.create(`restitution:antiblock_${color}`)
        .displayName(`${displayname} Antiblock`)
        .soundType(SoundType.WOOL)
        .tagBlock('minecraft:mineable/pickaxe')
        .property(BlockProperties.LIT)
        .lightLevel(1.0)
        .requiresTool(false)
        .textureAll(`restitution:block/${color}`)
        .notSolid()
        .opaque(false)
        .fullBlock(false)
        .defaultTranslucent()
}

StartupEvents.registry("block", (event) => {
    registerAntiblock(event, "black", "Black")
    registerAntiblock(event, "blue", "Blue")
    registerAntiblock(event, "brown", "Brown")
    registerAntiblock(event, "cyan", "Cyan")
    registerAntiblock(event, "green", "Green")
    registerAntiblock(event, "gray", "Gray")
    registerAntiblock(event, "lime", "Lime")
    registerAntiblock(event, "light_blue", "Light Blue")
    registerAntiblock(event, "light_gray", "Light Gray")
    registerAntiblock(event, "magenta", "Magenta")
    registerAntiblock(event, "orange", "Orange")
    registerAntiblock(event, "purple", "Purple")
    registerAntiblock(event, "red", "Red")
    registerAntiblock(event, "white", "White")
    registerAntiblock(event, "yellow", "Yellow")
    registerAntiblock(event, "pink", "Pink")
})